### ISSUE TITLE
Startup Javascript error

### ISSUE THREAD

**Issue by ericraymond** [davidferguson/pibakery#183]
When I run PiBakery2 bia `npm start` I get the following error at startup.  

```Uncaught Exception:
ReferenceError: app is not defined
    at createMenu (/src/labs/pibakery/main.js:205:14)
    at launchPiBakery (/src/labs/pibakery/main.js:162:3)
    at Object.<anonymous> (/src/labs/pibakery/main.js:97:3)
    at Object.<anonymous> (/src/labs/pibakery/main.js:245:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at finishedCheck (/src/labs/pibakery/start.js:51:5)
    at /src/labs/pibakery/lib/updates.js:59:9
    at /src/labs/pibakery/lib/settings.js:99:5
    at /src/labs/pibakery/lib/settings.js:58:5
    at /src/labs/pibakery/node_modules/jsonfile/index.js:43:5```

PiBakery works with no issues AFAIK.

**Comment by raiman264** [comment]
@ericraymond you just have to call it from `electron` added PR to fix that
